### ISSUE TITLE
Kernel size for MRELBP Median Filter is not necessarily shared for small and large images

### ISSUE THREAD

**Issue by OscarVanL** [MIPT-Oulu/LocalBinaryPattern#7]
Hi, just a quick query. I'm looking to implement MRELBP in Python so your codebase has been excellent as a reference.

I noticed in the file `LBP/LBPLibrary/Parameters.cs` you label the following parameters:

`W_c` as `Kernel size for median filter on center image.`

`W_r` as` Kernel size for median filter on small [0] and large [1] image.`

However when I compare this to the functions described in `Median Robust Extended Local Binary Pattern for Texture Classification` DOI 10.1109/TIP.2016.2522378 there is a discrepancy.

In the paper there is a diagram depicting the centre image, small images (at r1) and large images (at r2):
![image](https://user-images.githubusercontent.com/7999692/73665122-80513380-4698-11ea-8764-db5baa3001b1.png)

It seems the small image (orange) and large image (blue) do not necessarily share the same Kernel size. In this case, the center image and small image share the Kernel size for example.

Am I misinterpreting your annotations? Was there an intentional reason for this? Or is it an error?

Thanks!
Oscar

**Comment by sarytky** [comment]
Dear Oscar,

Thanks for your feedback! Indeed, the kernel sizes are not necessarily the same for the center, small and large radius. The file you are referring to contains some default parameters used in prototyping the LBP method, but they can be freely changed. Usually, most of these parameters are optimized with specific algorithms.

If you are interested, please take a look at [our recent study](https://github.com/MIPT-Oulu/3DHistoGrading) that utilizes similar methods (also in Python).

Best regards,
Santeri
